apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-binding-a
  namespace: default
subjects:
- kind: User
  name: "your-azure-ad-username@example.com"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: role-a
  apiGroup: rbac.authorization.k8s.io
